#if !defined(CHAD_INTERPRETER_BINARY_OP)
#error You must define CHAD_INTERPRETER_BINARY_OP before including this file
#endif

#ifndef CHAD_INTERPRETER_BINARY_OP_LAST
#define CHAD_INTERPRETER_BINARY_OP_LAST(X) CHAD_INTERPRETER_TOKEN(X)
#endif

CHAD_INTERPRETER_BINARY_OP(ADD, +)
CHAD_INTERPRETER_BINARY_OP(SUB, -)
CHAD_INTERPRETER_BINARY_OP(MUL, *)
CHAD_INTERPRETER_BINARY_OP(DIV, /)
CHAD_INTERPRETER_BINARY_OP(MODULO, %)
CHAD_INTERPRETER_BINARY_OP(AND, &&)
CHAD_INTERPRETER_BINARY_OP(OR, ||)
CHAD_INTERPRETER_BINARY_OP(EQUAL, ==)
CHAD_INTERPRETER_BINARY_OP(NOT_EQUAL, !=)
CHAD_INTERPRETER_BINARY_OP(GREATER, >)
CHAD_INTERPRETER_BINARY_OP(GREATER_EQUAL, >=)
CHAD_INTERPRETER_BINARY_OP(LESS, <)
CHAD_INTERPRETER_BINARY_OP(LESS_EQUAL, <=)

#undef CHAD_INTERPRETER_BINARY_OP
#undef CHAD_INTERPRETER_BINARY_OP_LAST
