#if !defined(CHAD_INTERPRETER_BUILTIN_FN)
#error You must define CHAD_INTERPRETER_TOKEN before including this file
#endif

#ifndef CHAD_INTERPRETER_BUILTIN_FN_LAST
#define CHAD_INTERPRETER_BUILTIN_FN_LAST(X) CHAD_INTERPRETER_BUILTIN_FN(X)
#endif

CHAD_INTERPRETER_BUILTIN_FN(PRINT, print)
CHAD_INTERPRETER_BUILTIN_FN(TYPE, type)
CHAD_INTERPRETER_BUILTIN_FN(AT, at)
CHAD_INTERPRETER_BUILTIN_FN(INPUT, input)
CHAD_INTERPRETER_BUILTIN_FN(LEN, len)

#undef CHAD_INTERPRETER_BUILTIN_FN
#undef CHAD_INTERPRETER_BUILTIN_FN_LAST
