#if !defined(PNS_INTERPRETER_RUNTIME_TYPE)
#error You must define PNS_INTERPRETER_TOKEN before including this file
#endif

#ifndef PNS_INTERPRETER_RUNTIME_TYPE_LAST
#define PNS_INTERPRETER_RUNTIME_TYPE_LAST(X) PNS_INTERPRETER_RUNTIME_TYPE(X)
#endif

PNS_INTERPRETER_RUNTIME_TYPE(STRING, str)
PNS_INTERPRETER_RUNTIME_TYPE(INTEGER, int)
PNS_INTERPRETER_RUNTIME_TYPE(FLOAT, float)
PNS_INTERPRETER_RUNTIME_TYPE(BOOLEAN, bool)

#undef PNS_INTERPRETER_RUNTIME_TYPE
#undef PNS_INTERPRETER_RUNTIME_TYPE_LAST
