#if !defined(CHAD_INTERPRETER_RUNTIME_TYPE)
#error You must define CHAD_INTERPRETER_TOKEN before including this file
#endif

#ifndef CHAD_INTERPRETER_RUNTIME_TYPE_LAST
#define CHAD_INTERPRETER_RUNTIME_TYPE_LAST(X) CHAD_INTERPRETER_RUNTIME_TYPE(X)
#endif

CHAD_INTERPRETER_RUNTIME_TYPE(STRING, str)
CHAD_INTERPRETER_RUNTIME_TYPE(INTEGER, int)
CHAD_INTERPRETER_RUNTIME_TYPE(FLOAT, float)
CHAD_INTERPRETER_RUNTIME_TYPE(BOOLEAN, bool)
CHAD_INTERPRETER_RUNTIME_TYPE(NULL, null)

#undef CHAD_INTERPRETER_RUNTIME_TYPE
#undef CHAD_INTERPRETER_RUNTIME_TYPE_LAST
