#if !defined(PNS_INTERPRETER_TOKEN)
#error You must define PNS_INTERPRETER_TOKEN before including this file
#endif

#ifndef PNS_INTERPRETER_TOKEN_LAST
#define PNS_INTERPRETER_TOKEN_LAST(X) PNS_INTERPRETER_TOKEN(X)
#endif

PNS_INTERPRETER_TOKEN(IDENTIFIER)
PNS_INTERPRETER_TOKEN(LET)
PNS_INTERPRETER_TOKEN(CONST)
PNS_INTERPRETER_TOKEN(IF)
PNS_INTERPRETER_TOKEN(PLUS)
PNS_INTERPRETER_TOKEN(MINUS)
PNS_INTERPRETER_TOKEN(MUL)
PNS_INTERPRETER_TOKEN(DIV)
PNS_INTERPRETER_TOKEN(OR)
PNS_INTERPRETER_TOKEN(AND)
PNS_INTERPRETER_TOKEN(NOT)
PNS_INTERPRETER_TOKEN(EQUAL)
PNS_INTERPRETER_TOKEN(OPEN_PAREN)
PNS_INTERPRETER_TOKEN(CLOSE_PAREN)
PNS_INTERPRETER_TOKEN(OPEN_BRACE)
PNS_INTERPRETER_TOKEN(CLOSE_BRACE)
PNS_INTERPRETER_TOKEN(BOOL_LITERAL)
PNS_INTERPRETER_TOKEN(INT_LITERAL)
PNS_INTERPRETER_TOKEN(STR_LITERAL)
PNS_INTERPRETER_TOKEN(SEMICOLON)
PNS_INTERPRETER_TOKEN(COLON)
PNS_INTERPRETER_TOKEN(EOS)

#undef PNS_INTERPRETER_TOKEN
#undef PNS_INTERPRETER_TOKEN_LAST