#if !defined(CHAD_INTERPRETER_UNARY_OP)
#error You must define CHAD_INTERPRETER_UNARY_OP before including this file
#endif

#ifndef CHAD_INTERPRETER_UNARY_OP_LAST
#define CHAD_INTERPRETER_UNARY_OP_LAST(X) CHAD_INTERPRETER_TOKEN(X)
#endif

CHAD_INTERPRETER_UNARY_OP(NEG, -)
CHAD_INTERPRETER_UNARY_OP(NOT, !)

#undef CHAD_INTERPRETER_UNARY_OP
#undef CHAD_INTERPRETER_UNARY_OP_LAST
